
include ../../conf/include.mk

EBIN_FILES = ../ebin/sgte_test_compile.beam \
		../ebin/sgte_test_render.beam \
		../ebin/sgte_test_map.beam \
		../ebin/gettext_test.beam \
		../ebin/sgeunit.beam \
		../ebin/run_tests.beam


all: $(EBIN_FILES)

clean:
	rm -f ../ebin/*.beam
