
include ../conf/include.mk

EBIN_FILES = ../ebin/sgte.beam \
		../ebin/sgte_render.beam \
		../ebin/sgte_parse.beam \
		../ebin/sgte_gettext.beam \
		../ebin/sgte_dict.beam


all: $(EBIN_FILES)

clean:
	rm -f ../ebin/*.beam
